### ISSUE TITLE
[Task] client - Nav 만들기

### ISSUE THREAD

**Issue by baemki** [codestates/THE-TOOPYO#10]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: add nav component

### TODO
1. [ ] login btn add
2. [ ] mypage add
3. [ ] 새 글 작성 btn add
4. [ ] 검색 btn add
5. [ ] logo btn add
6. [ ] CSS 다듬기 

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `Sprint 2`
- Urgency: `High`
