### ISSUE TITLE
[Task] client - Main page 만들기

### ISSUE THREAD

**Issue by baemki** [codestates/THE-TOOPYO#14]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: add main page

### TODO
1. [ ] mainipage, feed 등 기능 구현
2. [ ] 회원, 비회원 2가지로 나누기 (새 글 작성, 피드 클릭 제한)
2. [ ] 무한 스크롤 만들기
3. [ ] CSS 다듬기

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `Sprint 2`
- Urgency: `High`
