### ISSUE TITLE
[Task] client - cur content 만들기

### ISSUE THREAD

**Issue by baemki** [codestates/THE-TOOPYO#21]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: current content add

### TODO
2. [x] img 클릭시 투표
3. [ ] 게시글 구현
4. [ ] 본인 글일시 수정, 삭제 표시
5. [ ] 좋아요 수, 싫어요 수, 투표 수 표시
6. [ ] CSS 다듬기

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `Sprint 2`
- Urgency: `High`
