### ISSUE TITLE
[Task] client - Mycontent 만들기

### ISSUE THREAD

**Issue by baemki** [codestates/THE-TOOPYO#26]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: add mycontent

### TODO
1. [x] 내 글 보기 클릭 시 화면 전환
2. [x] 내 정보 클릭 시 다시 
3. [x] 안녕하세요, 00님
4. [x] 쓴 글 표시 및 글 마다 삭제 버튼
5. [x] CSS 다듬기

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `Sprint 2`
- Urgency: `High`
